# Generated by Django 3.1.1 on 2021-03-03 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_produto', models.CharField(max_length=100)),
                ('nome_produto', models.CharField(max_length=100)),
                ('valor_produto', models.CharField(max_length=10)),
                ('loja_produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yummy_register.loja')),
            ],
        ),
    ]
